/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedMyListRouteImport } from './routes/_authed/my-list'
import { Route as TitleMediaTypeIdRouteImport } from './routes/title.$mediaType.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyListRoute = AuthedMyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => AuthedRoute,
} as any)
const TitleMediaTypeIdRoute = TitleMediaTypeIdRouteImport.update({
  id: '/title/$mediaType/$id',
  path: '/title/$mediaType/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/home': typeof AuthedHomeRoute
  '/my-list': typeof AuthedMyListRoute
  '/title/$mediaType/$id': typeof TitleMediaTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/home': typeof AuthedHomeRoute
  '/my-list': typeof AuthedMyListRoute
  '/title/$mediaType/$id': typeof TitleMediaTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/my-list': typeof AuthedMyListRoute
  '/title/$mediaType/$id': typeof TitleMediaTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/search' | '/home' | '/my-list' | '/title/$mediaType/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/login' | '/search' | '/home' | '/my-list' | '/title/$mediaType/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/search'
    | '/_authed/home'
    | '/_authed/my-list'
    | '/title/$mediaType/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  TitleMediaTypeIdRoute: typeof TitleMediaTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my-list': {
      id: '/_authed/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof AuthedMyListRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/title/$mediaType/$id': {
      id: '/title/$mediaType/$id'
      path: '/title/$mediaType/$id'
      fullPath: '/title/$mediaType/$id'
      preLoaderRoute: typeof TitleMediaTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedMyListRoute: typeof AuthedMyListRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedMyListRoute: AuthedMyListRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  TitleMediaTypeIdRoute: TitleMediaTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
